### ISSUE TITLE
Uniffi doesn't construct exceptions properly in JVM

### ISSUE THREAD

**Issue by Dmitry-Borodin** [paritytech/parity-signer#1301]
ErrorDisplay is defined and Str as a Subclass. 
While in case of error ErrorDisplayed$Str is thrown and calling code receiving 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

Exception example 
```
Process: io.parity.signer, PID: 9371
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
                                                                                                    Caused by: io.parity.signer.uniffi.ErrorDisplayed$Str
                                                                                                    	at io.parity.signer.uniffi.FfiConverterTypeErrorDisplayed.read(signer.kt:5427)
                                                                                                    	at io.parity.signer.uniffi.FfiConverterTypeErrorDisplayed.read(signer.kt:5422)
                                                                                                    	at io.parity.signer.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(signer.kt:149)
                                                                                                    	at io.parity.signer.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(signer.kt:161)
                                                                                                    	at io.parity.signer.uniffi.FfiConverterTypeErrorDisplayed.liftFromRustBuffer(signer.kt:5422)
                                                                                                    	at io.parity.signer.uniffi.FfiConverterTypeErrorDisplayed.liftFromRustBuffer(signer.kt:5422)
                                                                                                    	at io.parity.signer.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(signer.kt:162)
                                                                                                    	at io.parity.signer.uniffi.FfiConverterTypeErrorDisplayed.lift(signer.kt:5422)
                                                                                                    	at io.parity.signer.uniffi.FfiConverterTypeErrorDisplayed.lift(signer.kt:5422)
                                                                                                    	at io.parity.signer.uniffi.ErrorDisplayed$ErrorHandler.lift(signer.kt:5416)
                                                                                                    	at io.parity.signer.uniffi.ErrorDisplayed$ErrorHandler.lift(signer.kt:5415)
                                                                                                    	at io.parity.signer.uniffi.SignerKt.historyGetWarnings(signer.kt:6716)
                                                                                                    	at io.parity.signer.models.SignerDataModel.getAlertState(SignerDataModel.kt:340)
                                                                                                    	at io.parity.signer.models.SignerDataModel.totalRefresh(SignerDataModel.kt:302)
                                                                                                    	at io.parity.signer.models.SignerDataModel$lateInit$1.invoke(SignerDataModel.kt:170)
                                                                                                    	at io.parity.signer.models.SignerDataModel$lateInit$1.invoke(SignerDataModel.kt:162)
                                                                                                    	at io.parity.signer.components.Authentication$authenticate$1.onAuthenticationSucceeded(Authentication.kt:53)
                                                                                                    	at androidx.biometric.BiometricFragment$9.run(BiometricFragment.java:907)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by montekki** [comment]
I really do not understand.


Here is the code in kotlin:

https://github.com/paritytech/parity-signer/blob/4bedb17f748fd8878a30ce394d13ef1d48cc9918/android/src/main/java/io/parity/signer/models/SignerDataModel.kt#L339-L345


So `historyGetWarnings` is a call to ffi that errors and throws the `ErrorDisplayed`. It is not caught -> your trace.

**Comment by Dmitry-Borodin** [comment]
1) First of all this PR is not about we shouldn't catch exceptions. It's about if we didn't - we will see what the error was. 

2) It is `java.lang.RuntimeException: java.lang.reflect.InvocationTargetException` that is thrown from this method.
`catch(e: ErrorDisplayed)` will not catch this exception. This is uniffi issue. 
And in general this message should go to Exception message argument (constructor argument if we'll use constructor), then it will be shown properly without hacks.

3) Another big topic of whether we should catch all exceptions and what we should do in this case on app side. It is independent of previous 2 (well, second need to be solved ) topics and I think we should discuss it separately. 
Because if I will just add catch and will do nothing - it will be even worse than crashing - app will just "freeze" kind of, because there will be no interaction on user entry. I think this topic should be discussed separately, best case if we'll divide errors by those that are recoverable and those that are not. And have clear understanding of how to recover from each.
