### ISSUE TITLE
Device error after successful Android build

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity-signer#214]
When I went to start contributing to a Parity Signer issue early this morning I encountered errors on my host machine, so I tried to set it up from scratch using the steps shown in "Details", but unfortunately I haven't overcome the error that I encountered:

Click the next "Details" link below to view my **Detailed Setup Steps** (EDIT: do not add the symlinks as suggested here, instead see the Solution in my subsequent comment and just use an absolute path to NDK and SDK)

<details><p><pre>

	* Download and install NDK r13b
		* Find the NDK version used successfully in the Gitlab CI - https://github.com/paritytech/parity-signer/blob/master/.gitlab-ci.yml
		* Find the link to that NDK version (i.e. 13b) - https://developer.android.com/ndk/downloads/older_releases
		* Download and install (be sure to check SHA1 matches)
			* Reference: https://www.lynxbee.com/how-to-install-android-ndk-on-ubuntu-16-04/

			```
			sudo mkdir -p ~/ndk && cd ~/ndk;
			wget -c https://dl.google.com/android/repository/android-ndk-r13b-darwin-x86_64.zip;
			sudo unzip android-ndk-r13b-darwin-x86_64.zip;
			rm android-ndk-r13b-darwin-x86_64.zip;
			echo 'export NDK_HOME="~/ndk/android-ndk-r13b"' >> ~/.bashrc
			echo 'export ANDROID_NDK_HOME="~/ndk/android-ndk-r13b"' >> ~/.bashrc
			echo 'export PATH=$PATH:~/ndk/android-ndk-r13b' >> ~/.bashrc
			source ~/.bashrc
			echo $NDK_HOME
			echo $ANDROID_NDK_HOME
			which ndk-build


			```

	* Switching from Java 11 to Java 8 by running alias `j8` before running npm run android (see https://www.kevinhooke.com/2017/10/05/switching-java-versions-on-mac-os/)

		```
		echo 'alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version"' >> ~/.bashrc
		echo 'alias j9="export JAVA_HOME=`/usr/libexec/java_home -v 9`; java -version"' >> ~/.bashrc
		echo 'alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version"' >> ~/.bashrc
		echo 'alias j7="export JAVA_HOME=`/usr/libexec/java_home -v 1.7`; java -version"' >> ~/.bashrc
		source ~/.bashrc

		j8
		```

	* Download and install the latest Android Studio
		* https://developer.android.com/studio/#downloads
		* References:
			* https://guides.codepath.com/android/installing-android-sdk-tools
			* https://developer.android.com/studio/intro/update#sdk-manager

		```
		cd ~/Downloads;
		wget -c https://dl.google.com/dl/android/studio/install/3.3.0.20/android-studio-ide-182.5199772-mac.dmg
		open android-studio-ide-182.5199772-mac.dmg
		```

		* Drag "Android Studio.app" into Applications folder and wait for it to transfer it

		* Open Android Studio

		* Choose default Android SDK Location "/Users/YOUR_USERNAME/Library/Android/sdk"

		* After it has finished the installation, choose:
			* "Configure > Preferences", which takes you to "Preferences > Android Studio > Preferences > Appearances & Behaviour > System Settings > Android SDK"
			* Select the tab "SDK Tools" to see that it has installed Android SDK Tools and Android Platform-Tools (which includes `adb`)

			* Note: DO NOT install NDK in these preferences, since it only allows you to install the latest version (whereas we've manually installed r13b separately)

	* Configure environment variables

		```
		echo 'export ANDROID_HOME="~/Library/Android/sdk"' >> ~/.bashrc
		echo 'export ANDROID_SDK_ROOT="~/Library/Android/sdk"' >> ~/.bashrc
		echo 'export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin' >> ~/.bashrc
		echo 'export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools' >> ~/.bashrc
		source ~/.bashrc
		echo $ANDROID_HOME
		echo $ANDROID_SDK_ROOT
		```

	* Accept Licenses

		```
		~/Library/Android/sdk/tools/bin/sdkmanager --licenses
		```

	* Go back to where your parity-signer directory is cloned.

		```
		cd ~/code/src/paritytech/parity-signer
		```

	* Install and configure compatible Rust version

		```
		curl https://sh.rustup.rs -sSf | sh
		rustup toolchain install 1.27.0
		rustup default 1.27.0
		```

	* Install compatible versions Node.js with NVM

		```
		nvm install v8.4.0
		nvm use v8.4.0
		node --version
		```

	* Install compatible version of Yarn using YVM
		```
		curl -fsSL https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.sh | bash
		source ~/.yvm/yvm.sh
		yvm install 1.6.0
		yvm use 1.6.0
		yarn --version
		```

	* Run the following script once that both NDK_HOME and ANDROID_HOME environment variables are set

		```
		./setup_macos.sh

		echo "ndk.dir=android-ndk-r13b" > android/local.properties
		echo "sdk.dir=sdk" >> android/local.properties
		```

	* Create Symlinks
		```
		ln -s ~/ndk/android-ndk-r13b ~/code/src/paritytech/parity-signer/android/
		ln -s ~/Library/Android/sdk ~/code/src/paritytech/parity-signer/android/
		```

	* On device enable "Developer options"
	* In "Developer options" I enabled "USB debugging"
	* In "Developer Options" click "Revoke USB debugging authorizations"
	* Reconnected the USB cable to the computer until it prompts "Allow USB debugging" on the mobile device and click "OK". It should say devices, not `unauthorized`. See https://facebook.github.io/react-native/docs/running-on-device
		```
		adb devices
		```

	* Resolve devices that are listed as `unauthorized` by following these instructions to pair the mobile device with your laptop https://stackoverflow.com/a/25546300/3208553. Only one mobile device may be connected at a time, and ensure that you device any version of Parity Signer v2.0-beta that is already on the mobile that was downloaded from the Google Playstore

	* Switch to compatible versions of Rust, Node.js, and Java dependencies

		```
		rustup default 1.27.0
		j8
                yvm use 1.6.0
		nvm use v8.4.0
		```

	* Run on Android device by entering the following. All commands are necessary to avoid a "Debug server host & port for device error. See https://facebook.github.io/react-native/docs/running-on-device#method-1-using-adb-reverse-recommended

		```
	yarn;
	adb kill-server;
	adb start-server;
	adb reverse tcp:8081 tcp:8081;
	adb reverse --list
	npm run android
		```

	* After a successful build the device should have had the Parity Signer icon added to it. Click the icon to run it.

	* Troubleshooting: Check your ~/.bashrc and ~/.bash_profile files to ensure that all the values set to environment variables are correct!

	* Show settings on device by either shaking the device to enter settings or if you haven't configured it to do that, then just type `adb shell input keyevent 82` on the computer.

	* Shake the device and choose "Reload"

	* Versions used

		```
		sw_vers;
		yarn --version; 
		node --version; 
		rustup --version;
		rustc --version;
		cargo --version;
		java -version;

		// Mac OS X 10.14
		// yarn 1.6.0
		// node v8.4.0
		// rustup 1.16.0
		// cargo 1.27.0
		// rustc 1.27.0
		// Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
		```
</pre></p></details>

After I run the step `npm run android` it displayed the following in the terminal indicating that it built successfully as shown below:

<details><p><pre>
...

Downloading bitflags v0.7.0                                                    
 Downloading deflate v0.7.19                                                    
 Downloading adler32 v1.0.3                                                     
    Finished release [optimized] target(s) in 14m 27.09s                        
PATH=/Users/scon/.nvm/versions/node/v8.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/Users/scon/.nvm/versions/node/v8.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/Users/scon/.yvm/versions/v1.6.0/bin:/Users/scon/.nvm/versions/node/v8.4.0/bin:/Users/scon/.cargo/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.cargo/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/scon/ndk/android-ndk-r16b:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:/Users/scon/Library/Android/ndk/android-ndk-r16b:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/sdk/tools:~/sdk/platform-tools:~/sdk/tools:~/sdk/platform-tools:~/sdk/tools:~/sdk/tools:~/sdk/platform-tools:~/sdk/tools/bin:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r13b:/Users/scon/ndk/android-ndk-r13b:/Users/scon/ndk/android-ndk-r16b:/Users/scon/ndk/android-ndk-r16b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r16b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r13b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r13b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/code/src/paritytech/parity-signer/rust/signer/../../NDK/arm/bin \
	CC=arm-linux-androideabi-gcc \
	CXX=arm-linux-androideabi-g++ \
	cargo build --target armv7-linux-androideabi --release
    Finished release [optimized] target(s) in 0.69s
PATH=/Users/scon/.nvm/versions/node/v8.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/Users/scon/.nvm/versions/node/v8.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/scon/code/src/paritytech/parity-signer/node_modules/.bin:/Users/scon/.yvm/versions/v1.6.0/bin:/Users/scon/.nvm/versions/node/v8.4.0/bin:/Users/scon/.cargo/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.cargo/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/llvm/bin:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.rbenv/shims:/Users/scon/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/scon/ndk/android-ndk-r16b:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:/Users/scon/Library/Android/ndk/android-ndk-r16b:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/sdk/tools:~/sdk/platform-tools:~/sdk/tools:~/sdk/platform-tools:~/sdk/tools:~/sdk/tools:~/sdk/platform-tools:~/sdk/tools/bin:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r13b:/Users/scon/ndk/android-ndk-r13b:/Users/scon/ndk/android-ndk-r16b:/Users/scon/ndk/android-ndk-r16b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r16b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r13b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/ndk/android-ndk-r13b:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/Users/scon/code/src/paritytech/parity-signer/rust/signer/../../NDK/x86/bin \
	CC=i686-linux-android-gcc \
	CXX=i686-linux-android-g++ \
	cargo build --target i686-linux-android --release --lib
    Finished release [optimized] target(s) in 0.40s
sh copy_android.sh
Scanning folders for symlinks in /Users/scon/code/src/paritytech/parity-signer/node_modules (36ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
The project name 'Parity Signer' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/4.4/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
        at settings_6nap3khn6d8ewwrmv8lkqea98.run(/Users/scon/code/src/paritytech/parity-signer/android/settings.gradle:1)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Configure project :app 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

> Configure project :react-native-camera 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-secure-storage 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-vector-icons 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
WARNING: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:installDebug 
Installing APK 'app-debug.apk' on 'SM-N950F - 8.0.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 23s
88 actionable tasks: 1 executed, 87 up-to-date
Running ~/Library/Android/sdk/platform-tools/adb -s 988a1644544349575a30 reverse tcp:8081 tcp:8081
Could not run adb reverse: spawnSync ~/Library/Android/sdk/platform-tools/adb ENOENT
Starting the app on 988a1644544349575a30 (~/Library/Android/sdk/platform-tools/adb -s 988a1644544349575a30 shell am start -n io.parity.signer/io.parity.signer.MainActivity)...
</pre></p></details>

But when I click the Parity Signer icon on my device (Samsun Galaxy 8 Note), it shows the following error, and it shows the same error if I press Reload, or a blank white screen if I press Dismiss:

<img width="411" alt="screen shot 2019-01-29 at 9 15 32 pm" src="https://user-images.githubusercontent.com/6226175/51901130-1067f780-240b-11e9-8969-7128af3b574d.png">

<img width="406" alt="screen shot 2019-01-29 at 9 15 40 pm" src="https://user-images.githubusercontent.com/6226175/51901133-11992480-240b-11e9-9cee-1427d199fd10.png">

Contents of my ~/.bashrc file:

```
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home"

# export ANDROID_NDK_HOME="/usr/local/share/android-ndk"
# export NDK_HOME="/usr/local/share/android-ndk"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export NDK_HOME="~/ndk/android-ndk-r13b"
export ANDROID_NDK_HOME="~/ndk/android-ndk-r13b"
export PATH=$PATH:~/ndk/android-ndk-r13b
export ANDROID_HOME="~/Library/Android/sdk"
export ANDROID_SDK_ROOT="~/Library/Android/sdk"
export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version"
alias j9="export JAVA_HOME=`/usr/libexec/java_home -v 9`; java -version"
alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version"
alias j7="export JAVA_HOME=`/usr/libexec/java_home -v 1.7`; java -version"

export YVM_DIR=/Users/scon/.yvm
[ -r $YVM_DIR/yvm.sh ] && source $YVM_DIR/yvm.sh
yvm use 1.10.1
```

**Comment by ltfschoen** [comment]
**Solution:**

1) **Removed the symlinks** that I had created to the NDK and SDK folders from the parity-signer/android/ directory.

2) Updated parity-signer/android/local.properties file so it contained absolute path to where I had installed the NDK and SDK
```
ndk.dir=/Users/scon/ndk/android-ndk-r13b
sdk.dir=/Users/scon/Library/Android/sdk
```
3) Switch to compatible versions of Rust, Node.js, and Java (using my custom alias) dependencies
```
rustup default 1.27.0
j8
yvm use 1.6.0
nvm use v8.4.0
```
<img width="805" alt="screen shot 2019-01-30 at 12 50 55 pm" src="https://user-images.githubusercontent.com/6226175/51953529-cfb2c180-2490-11e9-8de7-bed746edda67.png">

4) Run on Android device by entering the following
```
yarn;
adb kill-server;
adb start-server;
adb reverse tcp:8081 tcp:8081;
adb reverse --list
npm run android
```

But encountered error
<details><p><pre>
Metro Bundler ready.

Loading dependency graph...(node:41229) UnhandledPromiseRejectionWarning: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/jest-haste-map/build/index.js:572:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/jest-haste-map/build/index.js:683:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/jest-haste-map/build/index.js:280:21)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:41229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: bundling failed: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/jest-haste-map/build/index.js:572:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/jest-haste-map/build/index.js:683:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/scon/code/src/paritytech/parity-signer/node_modules/metro/node_modules/jest-haste-map/build/index.js:280:21)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

Loading dependency graph...::1 - - [30/Jan/2019:01:52:22 +0000] "GET /favicon.ico HTTP/1.1" 404 150 "http://localhost:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
</pre></p></details>

5) Installed watchman

```
brew install watchman
```

6) Re-run on Android device by entering the following again
```
yarn;
adb kill-server;
adb start-server;
adb reverse tcp:8081 tcp:8081;
adb reverse --list
npm run android
```

7) Success

<img width="753" alt="screen shot 2019-01-30 at 12 59 42 pm" src="https://user-images.githubusercontent.com/6226175/51953685-6b443200-2491-11e9-9265-2b4e83f1eb2a.png">

**Comment by ltfschoen** [comment]
Update: Tried repeating the "Initial success" steps, but now encountering the initial error again:

<details><p><pre>
> Task :app:compileDebugJavaWithJavac FAILED
/Users/scon/code/src/paritytech/parity-signer/android/app/src/main/java/io/parity/signer/EthkeyBridge.java:62: error: reference to reject is ambiguous
            promise.reject("invalid rlp", null, null);
                   ^
  both method reject(String,Throwable,WritableMap) in Promise and method reject(String,String,WritableMap) in Promise match
/Users/scon/code/src/paritytech/parity-signer/android/app/src/main/java/io/parity/signer/EthkeyBridge.java:97: error: reference to reject is ambiguous
            promise.reject("invalid password", null, null);
                   ^
  both method reject(String,Throwable,WritableMap) in Promise and method reject(String,String,WritableMap) in Promise match
2 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
54 actionable tasks: 1 executed, 53 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:591:13)
    at Object.execFileSync (child_process.js:611:13)
    at runOnAllDevices (/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/scon/code/src/paritytech/parity-signer/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NativeSigner@0.0.1 android: `npm run build-rust-android && react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the NativeSigner@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/scon/.npm/_logs/2019-01-30T03_01_27_282Z-debug.log
</pre></p></details>

**Comment by ltfschoen** [comment]
Specifically, the following error was triggered when I tried to update "react-native" from "0.55.3" to "0.58.3"

**Comment by ltfschoen** [comment]
<details><p><pre>
> Task :app:compileDebugJavaWithJavac FAILED
/Users/scon/code/src/paritytech/parity-signer/android/app/src/main/java/io/parity/signer/EthkeyBridge.java:62: error: reference to reject is ambiguous
            promise.reject("invalid rlp", null, null);
                   ^
  both method reject(String,Throwable,WritableMap) in Promise and method reject(String,String,WritableMap) in Promise match
/Users/scon/code/src/paritytech/parity-signer/android/app/src/main/java/io/parity/signer/EthkeyBridge.java:97: error: reference to reject is ambiguous
            promise.reject("invalid password", null, null);
                   ^
  both method reject(String,Throwable,WritableMap) in Promise and method reject(String,String,WritableMap) in Promise match
2 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
</pre></p></details>
