### ISSUE TITLE
Crash after entering pin to sign scanned transaction

### ISSUE THREAD

**Issue by bananer** [paritytech/parity-signer#62]
Here's what I did:

* set up parity on my laptop
* add a multi-sig watch address to parity
* compile and run native-signer on my phone and add the account which is part of the multi-sig
* add "external account" to parity, scanned account code from phone to laptop
* receive transaction request through parity
* choose to confirm transaction
* scan transaction qr from laptop to phone
* transaction details show up properly on phone
* enter pin to sign transaction

then native-signer crashes:

```
04-16 18:50:57.923  7303  7350 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7350 (mqt_native_modu)
04-16 18:50:58.024  1411  1411 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-16 18:50:58.024  1411  1411 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
04-16 18:50:58.024  1411  1411 F DEBUG   : Revision: '11'
04-16 18:50:58.024  1411  1411 F DEBUG   : ABI: 'arm'
04-16 18:50:58.024  1411  1411 F DEBUG   : pid: 7303, tid: 7350, name: mqt_native_modu  >>> com.nativesigner <<<
04-16 18:50:58.025  1411  1411 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-16 18:50:58.052  1411  1411 F DEBUG   :     r0 00000000  r1 00001cb6  r2 00000006  r3 9e97d978
04-16 18:50:58.052  1411  1411 F DEBUG   :     r4 9e97d980  r5 9e97d930  r6 0000000b  r7 0000010c
04-16 18:50:58.052  1411  1411 F DEBUG   :     r8 9cde13a0  r9 9eb05e28  sl 9e97cde4  fp 9e97c660
04-16 18:50:58.052  1411  1411 F DEBUG   :     ip 00000006  sp 9e97c610  lr b6cebb61  pc b6cedf50  cpsr 400f0010
04-16 18:50:58.072  1411  1411 F DEBUG   : 
04-16 18:50:58.072  1411  1411 F DEBUG   : backtrace:
04-16 18:50:58.072  1411  1411 F DEBUG   :     #00 pc 00041f50  /system/lib/libc.so (tgkill+12)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #01 pc 0003fb5d  /system/lib/libc.so (pthread_kill+32)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #04 pc 000174ac  /system/lib/libc.so (abort+4)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #05 pc 0005118c  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #06 pc 00051ee0  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #07 pc 00051d78  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #08 pc 00051bc8  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #09 pc 00051b04  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #10 pc 00051aa0  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #11 pc 0005cb80  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #12 pc 00005a44  /data/app/com.nativesigner-2/lib/arm/libsigner.so
04-16 18:50:58.072  1411  1411 F DEBUG   :     #13 pc 0000bdb8  /data/app/com.nativesigner-2/lib/arm/libsigner.so (Java_com_nativesigner_EthkeyBridge_ethkeyDecryptData+928)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #14 pc 00f14f05  /data/app/com.nativesigner-2/oat/arm/base.odex (offset 0x6b3000) (java.lang.String com.nativesigner.EthkeyBridge.ethkeyDecryptData(java.lang.String, java.lang.String)+112)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #15 pc 00f15457  /data/app/com.nativesigner-2/oat/arm/base.odex (offset 0x6b3000) (void com.nativesigner.EthkeyBridge.decryptData(java.lang.String, java.lang.String, com.facebook.react.bridge.Promise)+66)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #16 pc 000e6331  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #17 pc 004028a5  /system/lib/libart.so (art_quick_invoke_stub+188)
04-16 18:50:58.072  1411  1411 F DEBUG   :     #18 pc 00101e04  [stack:7350]
04-16 18:50:59.076  1902  7633 W ActivityManager:   Force finishing activity com.nativesigner/.MainActivity
04-16 18:50:59.077  1411  1411 F DEBUG   : 
04-16 18:50:59.077  1411  1411 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_02
04-16 18:50:59.077  1411  1411 E DEBUG   : AM write failed: Broken pipe
04-16 18:50:59.127  1902  1914 I WindowState: WIN DEATH: Window{216fa21 u0 com.nativesigner/com.nativesigner.MainActivity}
04-16 18:50:59.127  1902  2408 D GraphicsStats: Buffer count: 4
04-16 18:50:59.138  1902  2016 I OpenGLRenderer: Initialized EGL, version 1.4
04-16 18:50:59.177  1424  1424 I Zygote  : Process 7303 exited due to signal (6)
04-16 18:50:59.187  1902  2409 I ActivityManager: Process com.nativesigner (pid 7303) has died
04-16 18:50:59.187  1902  2409 D ActivityManager: cleanUpApplicationRecord -- 7303
04-16 18:50:59.666  1902  1936 W WindowAnimator: Failed to dispatch window animation state change.
04-16 18:50:59.666  1902  1936 W WindowAnimator: android.os.DeadObjectException
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-16 18:50:59.666  1902  1936 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-16 18:50:59.753  2451  2665 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-16 18:51:27.858  1902  1938 I PowerManagerService: Going to sleep due to screen timeout (uid 1000)...
04-16 18:51:27.859  1902  1938 I PowerManagerService: Sleeping (uid 1000)...
04-16 18:51:27.861  1902  1902 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 7303 uid 10083
04-16 18:51:28.425  1902  1938 V KeyguardServiceDelegate: onScreenTurnedOff()
04-16 18:51:28.444  1902  1936 I DisplayManagerService: Display device changed state: "Built-in Screen", OFF
04-16 18:51:28.447   181   181 D SurfaceFlinger: Set power mode=0, type=0 flinger=0xb6a64000
04-16 18:51:28.447   181   181 D qdhwcomposer: hwc_blank: Blanking display: 0
04-16 18:51:28.722   181   181 D qdhwcomposer: hwc_blank: Done blanking display: 0
04-16 18:51:28.724  1902  2042 D SurfaceControl: Excessive delay in setPowerMode(): 280ms
04-16 18:51:28.725  2676  2677 E ANDR-PERF-LOCK: Failed to apply optimization for resource: 4 level: 0
04-16 18:51:28.746  1902  2025 D WifiConfigStore: Retrieve network priorities after PNO.
04-16 18:51:28.747  1902  2025 E WifiStateMachine:  Fail to set up pno, want false now false
04-16 18:51:28.754  1414  1958 D audio_hw_primary: adev_set_parameters: enter: screen_state=off
04-16 18:51:33.064  2079  2079 D PhoneStatusBar: disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search quick_settings >
04-16 18:51:33.126  2079  2079 D PhoneStatusBar: disable: < expand ICONS alerts SYSTEM_INFO back HOME* RECENT* clock SEARCH* quick_settings >


```

**Comment by debris** [comment]
Thanks for report! I will look into it tomorrow

**Comment by debris** [comment]
I believe it's the same as #72 . Fixed in latest version (13) of android app
