### ISSUE TITLE
parity-signer-4.5.3-beta build failure

### ISSUE THREAD

**Issue by wojiaopaidaxing** [paritytech/parity-signer#867]
For safety reasons, I want to modify some things, but I can’t compile this release version

Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/chenshang/.gradle/caches/transforms-2/files-2.1/a3bbde232f973464fb72f60c806b3f10/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by Slesarew** [comment]
Try clearing gradle cache; I doubt somebody will be fixing build issues in legacy code at this point, sorry. It was a mess at some point, 4.6.2 fixed some build issues, maybe try it.

Development android version in #844 should be buildable now; it's far from release, but it has very basic functionality.

**Comment by wojiaopaidaxing** [comment]
![image](https://user-images.githubusercontent.com/9145559/140025020-374ab960-af04-4027-97a2-1b501ff6036b.png)

I built sccess,but run error, please help me 


> 2021-11-03 15:50:33.129 4714-4863/? E/unknown:ReactNative: Unable to download JS bundle
    com.facebook.react.common.DebugServerException: Could not connect to development server.
    
    Try the following to fix the issue:
    • Ensure that the packager server is running
    • Ensure that your device/emulator is connected to your machine and has USB debugging enabled - run 'adb devices' to see a list of connected devices
    • Ensure Airplane Mode is disabled
    • If you're on a physical device connected to the same machine, run 'adb reverse tcp:8081 tcp:8081' to forward requests from your device
    • If your device is on the same Wi-Fi network, set 'Debug server host & port for device' in 'Dev settings' to your machine's IP address and the port of the local dev server - e.g. 10.0.1.1:8081
    
    URL: http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false
        at com.facebook.react.devsupport.BundleDownloader$1.onFailure(BundleDownloader.java:129)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:211)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.ConnectException: Failed to connect to /10.0.2.2:8081
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.net.ConnectException: failed to connect to /10.0.2.2 (port 8081) from /10.0.2.16 (port 53622) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:287)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
        at libcore.io.IoBridge.connect(IoBridge.java:134)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167) 
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258) 
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) 
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:274)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:192) 
        at libcore.io.IoBridge.connect(IoBridge.java:134) 
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142) 
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390) 
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230) 
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212) 
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436) 
        at java.net.Socket.connect(Socket.java:621) 
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73) 
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247) 
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167) 
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258) 
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) 
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-11-03 15:50:33.142 4714-4714/? E/unknown:ReactNative: Exception in native call
    com.facebook.react.common.DebugServerException: Could not connect to development server.
    
    Try the following to fix the issue:
    • Ensure that the packager server is running
    • Ensure that your device/emulator is connected to your machine and has USB debugging enabled - run 'adb devices' to see a list of connected devices
    • Ensure Airplane Mode is disabled
    • If you're on a physical device connected to the same machine, run 'adb reverse tcp:8081 tcp:8081' to forward requests from your device
    • If your device is on the same Wi-Fi network, set 'Debug server host & port for device' in 'Dev settings' to your machine's IP address and the port of the local dev server - e.g. 10.0.1.1:8081
    
    URL: http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false
        at com.facebook.react.devsupport.BundleDownloader$1.onFailure(BundleDownloader.java:129)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:211)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.ConnectException: Failed to connect to /10.0.2.2:8081

**Comment by Slesarew** [comment]
Try bumping java version (to 11 I suppose) here:
 https://github.com/paritytech/parity-signer/blob/c6b30f5648f8a1abc6481695d747a9ed15c151d5/android/app/build.gradle#L129

Something like
```

compileOptions {
		sourceCompatibility JavaVersion.VERSION_11
		targetCompatibility JavaVersion.VERSION_11
	}
```

I've seen this error for some time coming and going; this is my theory on how to fix it permanently, but I haven't differential-tested it.

**Comment by wojiaopaidaxing** [comment]
> Try bumping java version (to 11 I suppose) here:
> 
> https://github.com/paritytech/parity-signer/blob/c6b30f5648f8a1abc6481695d747a9ed15c151d5/android/app/build.gradle#L129
> 
> Something like
> 
> ```
> 
> compileOptions {
> 		sourceCompatibility JavaVersion.VERSION_11
> 		targetCompatibility JavaVersion.VERSION_11
> 	}
> ```
> 
> I've seen this error for some time coming and going; this is my theory on how to fix it permanently, but I haven't differential-tested it.

It not work

**Comment by wojiaopaidaxing** [comment]
I resolve it 

```diff --git a/android/app/build.gradle b/android/app/build.gradle
index 20d4ada..4480de4 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -135,7 +135,7 @@ android {
         multiDexEnabled true
         minSdkVersion 18
         missingDimensionStrategy 'react-native-camera', 'general'
-        targetSdkVersion 28
+        targetSdkVersion 30
         versionCode 4503
         versionName "4.5.3"
         ndk {
@@ -215,9 +215,11 @@ dependencies {
     debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
         exclude group:'com.facebook.fbjni'
     }
-    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
-        exclude group:'com.facebook.flipper'
-    }
+
+		debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
+			exclude group:'com.facebook.flipper'
+			exclude group:'com.squareup.okhttp3', module:'okhttp'
+		}
     debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
         exclude group:'com.facebook.flipper'
     }
diff --git a/android/build.gradle b/android/build.gradle
index 14706fb..2ec3e2b 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -4,9 +4,10 @@ buildscript {
    ext {
         buildToolsVersion = "29.0.3"
         minSdkVersion = 18
-        compileSdkVersion = 29
-        targetSdkVersion = 29
+        compileSdkVersion = 30 
+        targetSdkVersion = 30
         kotlinVersion = '1.3.41'
+        androidXCore = "1.6.0"
     }
     repositories {
         google()
diff --git a/android/gradle.properties b/android/gradle.properties
index e3e72c0..f165949 100644
--- a/android/gradle.properties
+++ b/android/gradle.properties
@@ -18,9 +18,9 @@ org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryErro
 # org.gradle.parallel=true
 
 MYAPP_RELEASE_STORE_FILE=apk.keystore
-MYAPP_RELEASE_KEY_ALIAS=testing
-MYAPP_RELEASE_STORE_PASSWORD=testing
-MYAPP_RELEASE_KEY_PASSWORD=testing
+MYAPP_RELEASE_KEY_ALIAS=key0
+MYAPP_RELEASE_STORE_PASSWORD=11111111
+MYAPP_RELEASE_KEY_PASSWORD=11111111
 android.enableR8=false
 android.useAndroidX=true
 android.enableJetifier=true
diff --git a/app.json b/app.json
index b38b963..2b41be3 100644
--- a/app.json
+++ b/app.json
@@ -1,4 +1,7 @@
 {
   "name": "NativeSigner",
-  "displayName": "NativeSigner"
-}
\ No newline at end of file
+  "displayName": "NativeSigner",
+  "expo": {
+    "sdkVersion": "0.62.2"
+  }
+}
```

### Debug
##### 1. install react-native
npm install -g react-native-cli

##### 2. clear cache

`react-native start --reset-cache`

##### 3. debug android
`react-native run-android`

### Release 
##### 1. config your android signing keystore in parity-signer/android/gradle.properties

##### 2. build release apk
`
cd android & ./gradlew assembleRelease
`
or  use android studio generate signed apk

**Comment by Slesarew** [comment]
Great, thank you!

I'll leave this issue here until the real release. I will not update the legacy branch, it's frozen for history - feel free to fork.

Otherwise, please have a look at newly developed version of Signer, it should have all functionality of the old one by now. If you want to work on something that will be developed in future, you can start now.

**Comment by Slesarew** [comment]
unsupported version
